[build]
  functions = "backend"

[functions]
  external_node_modules = ["express", "bcrypt", "jsonwebtoken", "cors", "pg", "dotenv", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlify/:query"
  to = "https://www.google.com/search?q=:query"
  status = 200
  force = true
  proxy = true
